services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-maxpolak04}/tab_view:latest
    container_name: flask_app
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    logging:
      driver: "syslog"
      options:
        syslog-address: "unixgram:///dev/log"
        tag: "flask_app"
    volumes:
      - uploads_data:/app/tab_view/static/uploads
      - ./branding/default.png:/app/tab_view/static/assets/default.png:ro
      - ./branding/logo_black.png:/app/tab_view/static/img/logo_black.png:ro
      - ./branding/logo_white.png:/app/tab_view/static/img/logo_white.png:ro
    networks:
      - flasknet

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: tab_view
      MYSQL_USER: tab_view
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    logging:
      driver: "syslog"
      options:
        syslog-address: "unixgram:///dev/log"
        tag: "mysql_db"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - flasknet

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    logging:
      driver: "syslog"
      options:
        syslog-address: "unixgram:///dev/log"
        tag: "nginx_proxy"
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - flasknet

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    logging:
      driver: "syslog"
      options:
        syslog-address: "unixgram:///dev/log"
        tag: "redis_cache"
    ports:
      - "6379:6379"
    networks:
      - flasknet

volumes:
  db_data:
  uploads_data:

networks:
  flasknet: