services:
  web:
    ports: !reset []
    healthcheck:
      interval: 30s
      retries: 3
    logging:
      driver: "journald"
      options:
        tag: "flask_app"

  db:
    logging:
      driver: "journald"
      options:
        tag: "mysql_db"

  nginx:
    ports: !reset
      - "80:80"
    logging:
      driver: "journald"
      options:
        tag: "nginx_proxy"

  redis:
    logging:
      driver: "journald"
      options:
        tag: "redis_cache"
