"""Add group_id to events

Revision ID: 053560fd276a
Revises: b01c584ab065
Create Date: 2026-03-26 10:29:46.876464

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "053560fd276a"
down_revision = "b01c584ab065"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.String(length=36), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("group_id")

    # ### end Alembic commands ###
