"""Add clock field

Revision ID: 774249955761
Revises: 03a2579da45c
Create Date: 2026-04-23 11:26:49.208568

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "774249955761"
down_revision = "03a2579da45c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("show_clock", sa.Boolean(), nullable=True))

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("show_clock", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("show_clock")

    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_column("show_clock")

    # ### end Alembic commands ###
