"""Add new columns

Revision ID: 96b8ed9ae197
Revises: 774249955761
Create Date: 2026-05-13 12:18:46.522380

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "96b8ed9ae197"
down_revision = "774249955761"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("show_weather", sa.Boolean(), nullable=True))

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("show_weather", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("show_weather")

    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_column("show_weather")

    # ### end Alembic commands ###
