"""Add EventMedia table for playlist

Revision ID: a5e24037395e
Revises: 3019d4b87c13
Create Date: 2025-10-29 12:12:55.355530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5e24037395e'
down_revision = '3019d4b87c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('events_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('media_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('events_ibfk_2'), 'media', ['media_id'], ['id'])

    op.drop_table('event_media')
    # ### end Alembic commands ###
