"""Add device_url to Device

Revision ID: d39d88c75102
Revises: 851930efe87d
Create Date: 2025-08-18 14:07:30.925510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd39d88c75102'
down_revision = '851930efe87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_url', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('media_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['device_url'])
        batch_op.create_foreign_key(None, 'media', ['media_id'], ['id'])
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('media_id')
        batch_op.drop_column('device_url')

    op.drop_table('media')
    # ### end Alembic commands ###
