"""initial migration

Revision ID: f17969aa9417
Revises: d39d88c75102
Create Date: 2025-08-21 10:37:46.484116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f17969aa9417'
down_revision = 'd39d88c75102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('device_url', sa.String(length=200), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_url'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('device_url'))
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('device_url', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('media_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('device_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('device_url'), ['device_url'], unique=True)

    op.drop_table('devices')
    # ### end Alembic commands ###
